nameOverride: "squidflow"
fullnameOverride: "squidflow"
namespace: "squidflow"

createNamespace: false

backend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 38080
  image:
    repository: ghcr.io/squidflow/service
    tag: "v0.0.3"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  image:
    repository: ghcr.io/squidflow/web
    tag: "v0.0.1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: false

argocd:
  serverAddress: "argocd-server.argocd.svc.cluster.local:80"
  username: "admin"
  password: "yFFLNJ-WzpaBObTD"
  plaintext: false
  insecure: true
  grpcweb: true

gitops:
  mode: "pull_request"
  branch_prefix: "SQ-change"
  metarepo:
    remoteUrl: "ssh://git@github.com:SquidFlow/gitops.git"

ssh_known_hosts:
  - "[bitbucket.com]:7999 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H"

git:
  secrets:
    - name: "source-secret-rw-ssh"
      keyField: "id_rsa"
      mountPath: "id_rsa"
