apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "squidflow.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "squidflow.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "squidflow.fullname" . }}
  labels:
    {{- include "squidflow.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "argoproj.io"
    resources:
      - "applications"
      - "applicationsets"
      - "appprojects"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

  - apiGroups:
      - "argocd-addon.github.com"
    resources:
      - "applicationtemplates"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

  - apiGroups:
      - ""
    resources:
      - "secrets"
      - "configmaps"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"

  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "secrets"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "squidflow.fullname" . }}
  labels:
    {{- include "squidflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "squidflow.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "squidflow.fullname" . }}
    namespace: {{ .Values.namespace }}

