apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "squidflow.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "squidflow.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "squidflow.fullname" . }}
  labels:
    {{- include "squidflow.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "argoproj.io"
    resources:
      - "applications"
      - "applicationsets"
      - "appprojects"
    verbs:
      - "get"
      - "list"
      - "watch"

  - apiGroups:
      - ""
    resources:
      - "secrets"
      - "configmaps"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"

  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "secrets"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "squidflow.fullname" . }}
  labels:
    {{- include "squidflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "squidflow.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "squidflow.fullname" . }}
    namespace: {{ .Values.namespace }}

